# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.actionworks.flashsale.mybatis.entity

spring:
  application:
    # 应用名称
    name: flash-sale
  # mysql
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://localhost:3306/learn_mybatis?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis
  redis:
    host: 127.0.0.1
    password: xxx
    address: redis://127.0.0.1:6379
  cloud:
    sentinel:
      eager: true
      transport:
        port: 8083
        # sentinel dashboard的ip
        dashboard: 127.0.0.1:8083
        # sentinel的ip
        client-ip: 127.0.0.1
      datasource:
        flow:
          nacos:
            # nacos用户名和密码
            username: nacos
            password: nacos
            server-addr: 127.0.0.1:8848
            dataId: FY-FLASH-ITEM
            groupId: DEFAULT_GROUP
            rule-type: flow

# 应用服务 WEB 访问端口
server:
  port: 8090
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 500

# 配置mybatis打印SQL日志,其中路径为其Mapper接口所在的包
logging:
  level:
    com.actionworks.flashsale.persistence.mapper: debug

management:
  metrics:
    export:
      datadog:
        enabled: false
      prometheus:
        enabled: true
      jmx:
        enabled: true
    tags:
      application: ${spring.application.name}
