# mybatis
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.actionworks.flashsale.mybatis.entity

spring:
  application:
    # 应用名称
    name: flash-sale
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://localhost:3306/flash_sale?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: fangyuan
    password: Mysql1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 30
      max-total: 50
      max-idle: 40
      min-idle: 30
      max-wait-millis: 10000
  mvc:
    pathmatch:
      # 兼容 swagger 的配置
      matching-strategy: ant_path_matcher

# 应用服务 WEB 访问端口
server:
  port: 8090
  servlet:
    context-path: /api
  tomcat:
    threads:
      max: 500

# 配置mybatis打印SQL日志,其中路径为其Mapper接口所在的包
logging:
  level:
    com.actionworks.flashsale.infrastructure.persistence.mapper: debug

management:
  metrics:
    export:
      datadog:
        enabled: false
      prometheus:
        enabled: true
      jmx:
        enabled: true
    tags:
      application: ${spring.application.name}
